import Head from "next/head"
import Link from "next/link"
import { client } from "../../../../libs/client"
import { Pagination } from "../../../components/layout/Pagenation"
import BlogHeader from "../../../components/sections/BlogHeader"
import Footer from "../../../components/sections/Footer"

interface Article {
  id: string
  title: string
  createdAt: string
  body: string
}

interface Contents {
  contents: Article[]
}

const PER_PAGE = 5

export default function Home({
  blog,
  totalCount,
}: {
  blog: { id: string; title: string; createdAt: Date; body: string }[]
  totalCount: any
}) {
  return (
    <div>
      <Head>
        <title>blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BlogHeader />
      <div className='mx-auto max-w-screen-xl min-h-90'>
        <div className=' mx-6 md:mx-auto max-w-screen-md'>
          <ul>
            {blog.map((blog) => (
              <li className='mb-16' key={blog.id}>
                <p className='py-3 text-gray-400'>
                  {new Date(blog.createdAt).toLocaleDateString()}
                </p>
                <Link href={`/blog/${blog.id}`}>
                  <a className='block mb-6 text-2xl font-bold'>{blog.title}</a>
                </Link>
                <div className='text-gray-600 line-clamp-3'>
                  <div
                    dangerouslySetInnerHTML={{
                      __html: `${blog.body}`,
                    }}
                  />
                </div>
                <div className='text-right'>
                  <button className='py-0.5 px-2 bg-progress-thin-green hover:bg-progress-dark-green rounded-lg'>
                    <Link href={`/blog/${blog.id}`}>redemore</Link>
                  </button>
                </div>
              </li>
            ))}
          </ul>
          <Pagination totalCount={totalCount} />
        </div>
      </div>
      <Footer />
    </div>
  )
}

// 動的なページを作成
export const getStaticPaths = async () => {
  const key = {
    headers: { "X-API-KEY": process.env.API_KEY ?? "" },
  }

  const res = await fetch("https://uhoshi.microcms.io/api/v1/blog", key)

  const repos = await res.json()

  const pageNumbers = []

  const range = (start: any, end: any) => [...Array(end - start + 1)].map((_, i) => start + i)

  const paths = range(1, Math.ceil(repos.totalCount / PER_PAGE)).map((repo) => `/blog/page/${repo}`)

  return { paths, fallback: false }
}

// データをテンプレートに受け渡す部分の処理を記述します
export const getStaticProps = async (context: any) => {
  const data: Contents = await client.get({ endpoint: "blog" })
  const id = context.params.id

  const key = {
    headers: { "X-API-KEY": process.env.API_KEY ?? "" },
  }
  const contents = await fetch(
    `https://uhoshi.microcms.io/api/v1/blog?offset=${(id - 1) * 5}&limit=5`,
    key,
  )
    .then((res) => res.json())
    .catch(() => null)
  return {
    props: {
      blog: contents.contents,
      totalCount: contents.totalCount,
    },
  }
}
