import type { NextPage } from "next"
import Head from "next/head"
import styles from "../../styles/Home.module.css"
import About from "../components/sections/About"
import Eyecatch from "../components/sections/Eyecatch"
import Footer from "../components/sections/Footer"
import Header from "../components/sections/Header"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <Eyecatch />
      <About />
      <Footer />
    </div>
  )
}

export default Home
