import Head from "next/head"
import BlogHeader from "../components/sections/BlogHeader"
import Footer from "../components/sections/Footer"

const Products = () => {
  return (
    <div>
      <Head>
        <title>Products</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BlogHeader />
      <div className=''>Products comming soon</div>
      <Footer />
    </div>
  )
}

export default Products
