import Head from "next/head"

const Products = () => {
  return (
    <div>
      <Head>
        <title>Products</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className=''>Products comming soon</div>
    </div>
  )
}

export default Products
