import Head from "next/head"
import Image from "next/image"
import userIcon from "../../public/images/usericon.png"
import BlogHeader from "../components/sections/BlogHeader"
import Footer from "../components/sections/Footer"

const Profile = () => {
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BlogHeader />
      <div className='mx-auto max-w-screen-xl min-h-90'>
        <div className=' mx-6 md:mx-auto max-w-screen-md leading-loose'>
          <h1 className='pb-10 text-5xl font-bold'>Profile</h1>
          <div className='pb-6 text-center'>
            <Image src={userIcon} width={200} height={200} className='block' alt='logo' />
          </div>
          <div className='pb-8'>
            <h2 className='text-2xl font-bold'>基本情報</h2>
            <hr className='pb-6 border-back-green' />
            <p>大学3年生のu-Hoshiと申します。(23卒)</p>
            <p>現在は都内の報道系のベンチャー企業でフロントエンドの実装を担当しています。</p>
            <p>
              ユーザーとコミュニケーションをとり、そのから課題を見つけ、それを改善していくのが好きです。
            </p>
          </div>
          <div className='pb-8'>
            <h2 className='text-2xl font-bold'>経歴</h2>
            <hr className='pb-6 border-back-green' />
            <ul>
              <div>
                <li>2021年 9月〜 現在</li>
                <li> 都内の報道系のベンチャー企業でフロントエンドの実装を担当</li>
              </div>
              <div>
                <li>2021年 9月</li>
                <li>
                  技育展登壇 <a href='https://github.com/u-Hoshi/mokumokuApp'>もくスケ</a>
                </li>
              </div>
              <div>
                <li>2021年 5月〜7月</li>
                <li>都内のEdTech企業でフロントエンドの実装及び要件定義</li>
              </div>
              <div>
                <li>2019年 12月〜2021年 4月</li>
                <li>都内のEdTech企業の営業、CS</li>
              </div>
            </ul>
          </div>
          <div className='pb-8'>
            <h2 className='text-2xl font-bold'>趣味</h2>
            <hr className='pb-6 border-back-green' />
            <ul>
              <li>サイクリング：orbea乗りです。</li>
              <li>スノーボード：都合がつけば北海道で滑ってます。</li>
              <li>アニメ：好きなジャンル(青春部活、ラブコメ、異世界、萌え、スポーツ)</li>
            </ul>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default Profile
