import Head from "next/head"

const Profile = () => {
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className=''>Profile comming soon</div>
    </div>
  )
}

export default Profile
