name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install, build
        run: 
          npm install
          npm run build
          env:
            API_KEY: ${{ secrets.X_API_KEY }}
            X_API_KEY: ${{ secrets.X_API_KEY }}
            serviceDomain: ${{ secrets.SERVICEDOMAIN }}
            apiKey: ${{ secrets.APIKEY }}

      - name: run Lighthouse CI
        run:
          npm install -g @lhci/cli@0.8.x
          lhci autorun
